 Data Type of list_ and array_list
python
Copy code
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_)

# Print data types
print(f"The data type of list_ is: {type(list_)}")
print(f"The data type of array_list is: {type(array_list)}")
Output:

kotlin
Copy code
The data type of list_ is: <class 'list'>
The data type of array_list is: <class 'numpy.ndarray'>
Q2. Data Type of Each Element in list_ and array_list
python
Copy code
# Data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Data types of elements in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))
Output:

arduino
Copy code
Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
Q3. Change array_list Data Type to int
python
Copy code
# Changing array_list to int type
array_list = np.array(object = list_, dtype = int)

# Data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Data types of elements in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))
Output:

arduino
Copy code
Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
The data type of elements in list_ remains str, while the data type of elements in array_list changes to int (numpy.int64).

Q4. Characteristics of num_array
python
Copy code
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object = num_list)

# (i) Shape
print(f"The shape of num_array is: {num_array.shape}")

# (ii) Size
print(f"The size of num_array is: {num_array.size}")
Output:

csharp
Copy code
The shape of num_array is: (2, 3)
The size of num_array is: 6
Q5. Create a 3x3 Matrix of Zeros
python
Copy code
zero_matrix = np.zeros((3, 3))
print(zero_matrix)
Output:

lua
Copy code
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Q6. Create a 5x5 Identity Matrix
python
Copy code
identity_matrix = np.eye(5)
print(identity_matrix)
Output:

css
Copy code
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]





